### ISSUE TITLE
Create CI/CD pipeline

### ISSUE THREAD

**Issue by shuaibq3** [CraftsmenLtd/BloodConnect#17]
Github actions to execute the tests, unit, integration, end-to-end. We can improve the pipeline in future as the scope and codebase grows

### What CI/CD pipeline will do?
1. Lint code
2. Lint terraform
3. Unit tests and measure code coverage
4. Integration test (future)
5. Security check (future)
6. Build/package libs/docker image if necessary

### Task
1. Make a github action
2. Use separate steps for linting and testing etc.
3. For dev branches it will only check lint, tests and security
4. For master branch, it will provide a report if the master is deployable
5. If code is pushed to master, it will deploy to dev branch
6. For any git release tag, it will deploy to prod depending on tag

**Comment by melon-ruet** [comment]
Proposed task for now

- Discard Python latest version and checkov for now. Because python latest version is used for checkov and python latest version build and install takes a lot of time of docker build. Will create a separate ticket for it.
- Make a build/deployment pipeline ASAP which do not need to be perfect because devs are waitting to start the main tasks of the project asap.
- There will be no integration test for now. Devs will manually test that in development environment.
